name: ShrimpShack
favicon: null
layout_spectrum: 0.05711859907023609
typography_spectrum: 0.7958059315569699
title: 'Shrimp Shack savory broth spice pack - make your own!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0065b3'
    - '#ed1b24'
    - '#8395a2'
    - '#000000'
  brandStrength: 0.5163078117184341
  lightness: 0.5057529064361006
  saturation: 0.7605490856803954
  rhythmicContrast: 0.5583015440497547
purpose: []
