name: ShrimpShack
favicon: null
layout_spectrum: 0.74185
typography_spectrum: 0.7958059315569699
title: 'Shrimp Shack spice pack - make your own!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0065b3'
    - '#ec1d25'
    - '#012858'
    - '#b7c9db'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.7605490856803954
  rhythmicContrast: 0.5
purpose: []
